name: Check user credits

on:
  schedule:
  - cron: "0 * * * *"
  workflow_dispatch:

env:
  NEXT_API_URL: https://staging.app.diversified.fi/api

jobs:
  build:
    name: Run Script
    runs-on: ubuntu-latest
    steps:
      - name: Run Script
        run: |
          curl -X GET "$NEXT_API_URL/jobs/check-user-credits" -H "Authorization: Bearer ${{ secrets.API_SECRET_KEY }}"

