name: Sync All Prices

defaults:
  run:
    working-directory: apps/web

on:
  workflow_dispatch:

jobs:
  build:
    name: Run Script
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable
        env:
          CI: TRUE

      - name: Run Script
        env:
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
          CI: TRUE
        run: node scripts/update-all-prices.js
